// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduMo0kJUZ9-lTDmNen5iihRkxOmmDi4U',
    appId: '1:504020085047:web:440dd22a31c4b44c1e92b2',
    messagingSenderId: '504020085047',
    projectId: 'meteogarden-f3c99',
    authDomain: 'meteogarden-f3c99.firebaseapp.com',
    storageBucket: 'meteogarden-f3c99.firebasestorage.app',
    measurementId: 'G-4G0HCDSQRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0tJbGmMfno4pLJ9FjTLL-KjHPeW6B9Fc',
    appId: '1:504020085047:android:358176e91256b6a81e92b2',
    messagingSenderId: '504020085047',
    projectId: 'meteogarden-f3c99',
    storageBucket: 'meteogarden-f3c99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpX0puF37uwfgn3_g4u6efNtExOxXKMU',
    appId: '1:504020085047:ios:01cb64cb7487c22e1e92b2',
    messagingSenderId: '504020085047',
    projectId: 'meteogarden-f3c99',
    storageBucket: 'meteogarden-f3c99.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgpX0puF37uwfgn3_g4u6efNtExOxXKMU',
    appId: '1:504020085047:ios:01cb64cb7487c22e1e92b2',
    messagingSenderId: '504020085047',
    projectId: 'meteogarden-f3c99',
    storageBucket: 'meteogarden-f3c99.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCduMo0kJUZ9-lTDmNen5iihRkxOmmDi4U',
    appId: '1:504020085047:web:a4f1402329dded011e92b2',
    messagingSenderId: '504020085047',
    projectId: 'meteogarden-f3c99',
    authDomain: 'meteogarden-f3c99.firebaseapp.com',
    storageBucket: 'meteogarden-f3c99.firebasestorage.app',
    measurementId: 'G-VFPG40YSNZ',
  );
}
