name: Frontend CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    name: Analyze and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

  distribute:
    name: Build and distribute APK
    needs: ci
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release \
          --dart-define=API_URL=http://nattech.fib.upc.edu:40450

      - name: Upload APK as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meteogarden-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk

